import type { Project } from './types';

export const projects: Project[] = [
  {
    id: 'atm',
    name: 'Algorithm Throughput Modeler — Thermo Fisher Scientific',
    short: 'ATM (Thermo Fisher)',
    employer: 'Thermo Fisher (Contract)',
    period: 'Jan–Oct 2025',
    oneLiner:
      'Built software quality tooling solo — Activity Diagram extraction from C# AST + telemetry-driven performance modelling — eliminating 90% of physical TEM test time.',
    metric: '80% reduction in physical performance verification time',
    tech: ['Python', 'C# .NET', 'AST', 'PlantUML', 'Flamegraph', 'OpenTelemetry'],
    tags: ['qa', 'backend', 'product'],
    isPurePE: true,
  },
  {
    id: 'ev-fleet',
    name: 'EV Fleet Dashboard — Alltrons',
    short: 'EV Fleet',
    employer: 'Alltrons',
    period: 'Jan–Mar 2026',
    oneLiner:
      'Architected and delivered a full-stack IoT dashboard end-to-end: real-time location mapping, ETL pipelines, and CAN-bus telemetry translated into fleet business insights.',
    metric: 'Solo full-stack ownership across AWS, Laravel, React, Terraform, CAN-bus ETL',
    tech: ['Laravel', 'React', 'AWS', 'Amazon Athena', 'CAN bus', 'ETL', 'Docker', 'Terraform'],
    tags: ['backend', 'fullstack', 'product'],
    isPurePE: true,
  },
  {
    id: 'secure-iot',
    name: 'Secure Offline IoT Bridge — Alltrons × Kayle Knops Holding (WBSO 2026-1)',
    short: 'Secure IoT Bridge',
    employer: 'Alltrons',
    period: 'Jun 2026 – present',
    oneLiner:
      'R&D Architect for a cryptographic trust chain between a trusted server and an offline IoT device relayed via untrusted BLE phone — without a real-time clock, without per-token state, on commodity silicon.',
    metric: 'Signed CBOR tokens · RSA-3072 via ESP32-S3 DS peripheral · monotonic-counter O(1) replay defence · dual-signed rotation artifacts',
    tech: ['ESP32-S3', 'BLE', 'CBOR', 'RSA-3072', 'eFuse', 'HAL'],
    tags: ['embedded', 'backend', 'product'],
    isPurePE: true,
  },
  {
    id: 'hasrul-buzz',
    name: 'hasrul.buzz — Gamified Personal Site with Persona Routing',
    short: 'hasrul.buzz',
    employer: 'Personal',
    period: 'Jun 2026 - present',
    oneLiner:
      'Demonstrates product judgment through a persona-routed site where the game (not reading) is the default landing — enabling recruiters, founders, and casual visitors to self-select their journey. One content model, three render skins; 3-layer architecture (Content/Routing/Render) reused across game and readable site.',
    metric: 'Persona-driven game-first landing with adaptive content, mobile touch controls (D-pad), onboarding flow (scenes ①–②), cartographic design language',
    tech: ['Vite', 'React', 'TypeScript', 'SVG', 'CSS Grid'],
    tags: ['product', 'fullstack'],
    isPurePE: true,
  },
  {
    id: 'alphatheta',
    name: 'AlphaTheta (Pioneer DJ) Warranty & Service Support System — Alltrons',
    short: 'AlphaTheta Warranty',
    employer: 'Alltrons',
    period: 'Feb–Mar 2026',
    oneLiner:
      'Global warranty-claim and service-parts system for AlphaTheta (Pioneer DJ) — worldwide service operations across international warehouses, couriers, distributors, dealers, and authorised service centres; integrated with Obligato (Hitachi) ERP.',
    metric: 'Symfony · MySQL · JavaScript · Docker · Obligato (Hitachi) ERP integration',
    tech: ['Symfony', 'MySQL', 'JavaScript', 'Docker'],
    tags: ['fullstack'],
  },
  {
    id: 'speechlabel',
    name: 'Speechlabel — Accessibility Mobile App (Android & iOS) — Alltrons',
    short: 'Speechlabel',
    employer: 'Alltrons',
    period: 'Mar–Apr 2026',
    oneLiner:
      'Cross-platform Android & iOS accessibility app using QR/NFC scanning to help people with low-vision identify objects in their environment.',
    metric: 'Kotlin (Android) · Swift (iOS) · QR/NFC · solo IC delivery',
    tech: ['Kotlin', 'Android', 'Swift', 'iOS', 'QR', 'NFC'],
    tags: ['fullstack'],
  },
  {
    id: 'mifare',
    name: 'MIFARE Smart-Lock Integration — Alltrons',
    short: 'MIFARE Lock',
    employer: 'Alltrons',
    period: 'Apr–May 2026',
    oneLiner:
      'Contactless MIFARE unlock with full lock-sequence parity (solenoid, LEDs, Hall sensor auto-relock) across 3 firmware stacks — STM32 ST HAL, nRF52833 Zephyr RTOS, ESP32 ESP-IDF — via I²C and serial daisy chain.',
    metric: '3 hardware platforms, zero mobile/backend dependency',
    tech: ['STM32', 'nRF52833', 'ESP32', 'Zephyr RTOS', 'ESP-IDF', 'MIFARE', 'I²C'],
    tags: ['embedded'],
  },
  {
    id: 'transjakarta',
    name: 'Transjakarta Bus Operation Management System — Ecomindo',
    short: 'Transjakarta',
    employer: 'Ecomindo',
    period: '2021–2022',
    oneLiner:
      'Scrum Master + Architect. Replaced Moovit API with a custom high-performance distributed real-time GPS platform.',
    metric: '1M+ daily commuters · 7,000+ buses',
    tech: ['C# .NET', 'Web API', 'React', 'Kafka', 'PostgreSQL'],
    tags: ['backend', 'fullstack', 'pm', 'techlead'],
  },
  {
    id: 'kawan-lama',
    name: 'Kawan Lama Group DevSecOps Framework — Ecomindo',
    short: 'Kawan Lama DevSecOps',
    employer: 'Ecomindo',
    period: '2023',
    oneLiner:
      'Architecture lead for a company-wide DevSecOps framework standardising development, security, and observability across 30+ retail and F&B brands.',
    metric: '50+ engineers · 9 teams · 30+ brands',
    tech: ['C# .NET', 'React', 'Kafka', 'Redis', 'Elasticsearch', 'MongoDB', 'Azure', 'PostgreSQL'],
    tags: ['backend', 'fullstack', 'techlead', 'qa'],
  },
  {
    id: 'pintar',
    name: 'PINTAR — PLN National Land Clearance Monitoring',
    short: 'PINTAR',
    employer: 'PT PLN Enjiniring',
    period: '2014–2018',
    oneLiner:
      'PM + Analyst + Architect on Indonesia\'s national 35GW power programme monitoring platform — integrated with Accenture PMO and PLN holding SAP.',
    metric: '18 regional construction offices · 4-year delivery',
    tech: ['PHP', 'CodeIgniter', 'SQL', 'SAP'],
    tags: ['backend', 'pm', 'techlead'],
  },
  {
    id: 'prima',
    name: 'PRIMA — Integrated Project Monitoring — PLN Enjiniring',
    short: 'PRIMA',
    employer: 'PT PLN Enjiniring',
    period: '2013',
    oneLiner:
      'Expeditor + Analyst + SE on a 24-person implementation team. Year-one result: €100K+ in financial anomalies surfaced, €200K write-off prevented.',
    metric: '€200K write-off prevented · €100K+ anomalies detected',
    tech: ['.NET', 'SQL Server', 'SharePoint'],
    tags: ['backend', 'qa', 'pm'],
  },
  {
    id: 'has-green',
    name: 'Brush Usage Detection — HAS Green Academy (TU/e EngD)',
    short: 'HAS Green Academy',
    employer: 'TU Eindhoven',
    period: 'May–Jun 2024',
    oneLiner:
      'Test Manager + SE. Automated cow-welfare detection system; delivered 90% pytest coverage and 20% accuracy improvement in 8 weeks.',
    metric: '90% pytest coverage · 20% accuracy improvement',
    tech: ['Python', 'pytest', 'IoT', 'Machine Learning'],
    tags: ['qa', 'backend'],
  },
];
