// AUTO-GENERATED by scripts/build-projects.mjs from the private projects.csv.
// Do not edit by hand. Regenerate with: npm run build:projects
// Maps a technology -> the projects (career-wide) that used it.

export const techIndex: Record<string, string[]> = {
  "ESP32": [
    "MIFARE-to-Smart-Lock Integration",
    "Secure Offline IoT Bridge"
  ],
  "ESP32-S3": [
    "Secure Offline IoT Bridge"
  ],
  "BLE": [
    "Secure Offline IoT Bridge"
  ],
  "NFC": [
    "MIFARE-to-Smart-Lock Integration",
    "Secure Offline IoT Bridge",
    "Speechlabel"
  ],
  "QR": [
    "Secure Offline IoT Bridge",
    "Speechlabel"
  ],
  "CBOR": [
    "Secure Offline IoT Bridge"
  ],
  "RSA-3072": [
    "Secure Offline IoT Bridge"
  ],
  "Ed25519": [
    "Secure Offline IoT Bridge"
  ],
  "eFuse": [
    "Secure Offline IoT Bridge"
  ],
  "HAL": [
    "MIFARE-to-Smart-Lock Integration",
    "Secure Offline IoT Bridge"
  ],
  "STM32": [
    "MIFARE-to-Smart-Lock Integration"
  ],
  "nRF52833": [
    "MIFARE-to-Smart-Lock Integration"
  ],
  "Zephyr RTOS": [
    "MIFARE-to-Smart-Lock Integration"
  ],
  "ESP-IDF": [
    "MIFARE-to-Smart-Lock Integration"
  ],
  "FreeRTOS": [
    "MIFARE-to-Smart-Lock Integration"
  ],
  "ST HAL": [
    "MIFARE-to-Smart-Lock Integration"
  ],
  "MIFARE": [
    "MIFARE-to-Smart-Lock Integration"
  ],
  "I²C": [
    "MIFARE-to-Smart-Lock Integration"
  ],
  "RFID/NFC": [
    "MIFARE-to-Smart-Lock Integration"
  ],
  "Symfony": [
    "AlphaTheta Warranty & Service Support System"
  ],
  "JavaScript": [
    "AlphaTheta Warranty & Service Support System"
  ],
  "MySQL": [
    "AlphaTheta Warranty & Service Support System"
  ],
  "Docker": [
    "AlphaTheta Warranty & Service Support System",
    "EV Fleet Dashboard",
    "Gitlab & Docker Implementation",
    "PT PLN Enjiniring",
    "SWAP Store"
  ],
  "Laravel": [
    "EV Fleet Dashboard"
  ],
  "React": [
    "Bus Operation Management System",
    "EV Fleet Dashboard",
    "Framework Foundation"
  ],
  "AWS": [
    "EV Fleet Dashboard"
  ],
  "Amazon Athena": [
    "EV Fleet Dashboard"
  ],
  "Terraform": [
    "EV Fleet Dashboard"
  ],
  "ETL": [
    "EV Fleet Dashboard"
  ],
  "CAN bus": [
    "EV Fleet Dashboard"
  ],
  "IoT": [
    "Brush Usage Detection in Dairy Farm",
    "EV Fleet Dashboard"
  ],
  "C# .NET": [
    "Algorithm Throughput Modeler",
    "Bus Operation Management System",
    "Framework Foundation"
  ],
  ".NET": [
    "Algorithm Throughput Modeler",
    "Bus Operation Management System",
    "Framework Foundation",
    "Project Integrated Monitoring Application",
    "PT PLN Enjiniring"
  ],
  "Python": [
    "AI-Powered Accounting System with SQL Agent Integr…",
    "Algorithm Throughput Modeler",
    "Brush Usage Detection in Dairy Farm",
    "SWAP Store",
    "TV PIN Brute-Forcer",
    "WWF Forest Foresight"
  ],
  "OpenTelemetry": [
    "Algorithm Throughput Modeler"
  ],
  "Flamegraph": [
    "Algorithm Throughput Modeler"
  ],
  "AST": [
    "Algorithm Throughput Modeler"
  ],
  "PlantUML": [
    "Algorithm Throughput Modeler"
  ],
  "Databricks": [
    "WWF Forest Foresight"
  ],
  "MLflow": [
    "WWF Forest Foresight"
  ],
  "GIS": [
    "WWF Forest Foresight"
  ],
  "R": [
    "WWF Forest Foresight"
  ],
  "pytest": [
    "Brush Usage Detection in Dairy Farm"
  ],
  "Machine Learning": [
    "Brush Usage Detection in Dairy Farm"
  ],
  "Web API": [
    "Bus Operation Management System",
    "SWAP Store"
  ],
  "Angular": [
    "SWAP Store"
  ],
  "Kubernetes": [
    "SWAP Store"
  ],
  "SQL": [
    "AI-Powered Accounting System with SQL Agent Integr…",
    "Attendance & Biometric System",
    "Business Trip Information System",
    "Cash Recovery Rate",
    "Engineer Workload System",
    "Framework Foundation",
    "Land Clearance and Permit Monitoring",
    "PRIMA Reminder",
    "PRIMA Report",
    "Project Integrated Monitoring Application",
    "Risk Control System",
    "Risk Management System",
    "Sales Management System",
    "TICMI Data Platform"
  ],
  "SQL Server": [
    "Framework Foundation",
    "Project Integrated Monitoring Application"
  ],
  "PostgreSQL": [
    "Bus Operation Management System",
    "Framework Foundation",
    "Memo and Letter System"
  ],
  "MongoDB": [
    "Framework Foundation"
  ],
  "Redis": [
    "Framework Foundation"
  ],
  "Elasticsearch": [
    "Framework Foundation"
  ],
  "Kafka": [
    "Bus Operation Management System",
    "Framework Foundation"
  ],
  "Azure": [
    "Azure AD & B2C Implementation with Duende",
    "Framework Foundation"
  ],
  "Grafana": [
    "Framework Foundation"
  ],
  "GCP": [
    "TICMI Data Platform"
  ],
  "GitLab": [
    "Gitlab & Docker Implementation",
    "PT PLN Enjiniring"
  ],
  "Java": [
    "Cash Recovery Rate",
    "Document Management System",
    "Engineer Workload System",
    "Memo and Letter System",
    "PRIMA Report",
    "PT PLN Enjiniring",
    "SID Simulation System Java Bridge & API",
    "Virtual Cubicle"
  ],
  "Oracle": [
    "Virtual Cubicle"
  ],
  "New Relic": [
    "Virtual Cubicle"
  ],
  "SAP": [
    "ERP Implementation",
    "Land Clearance and Permit Monitoring",
    "PT PLN Enjiniring",
    "Virtual Cubicle"
  ],
  "SAP Business One": [
    "ERP Implementation",
    "Virtual Cubicle"
  ],
  "PHP": [
    "Business Trip Information System",
    "Land Clearance and Permit Monitoring",
    "PRIMA Reminder",
    "Risk Control System",
    "Risk Management System",
    "Sales Management System"
  ],
  "CodeIgniter": [
    "Land Clearance and Permit Monitoring"
  ],
  "Alfresco": [
    "Document Management System",
    "PT PLN Enjiniring"
  ],
  "SharePoint": [
    "Project Integrated Monitoring Application"
  ]
};
